# Generated by Django 5.2.16 on 2026-07-21 16:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "license_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "carrier_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "carrier_main_office",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "home_terminal_tz",
                    models.CharField(
                        default="America/Chicago",
                        help_text="IANA timezone, e.g. America/Chicago",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("truck_number", models.CharField(max_length=50)),
                (
                    "trailer_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "license_plate",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "license_state",
                    models.CharField(blank=True, default="", max_length=2),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_location_label", models.CharField(max_length=300)),
                ("current_location_lat", models.FloatField()),
                ("current_location_lng", models.FloatField()),
                ("pickup_label", models.CharField(max_length=300)),
                ("pickup_lat", models.FloatField()),
                ("pickup_lng", models.FloatField()),
                ("dropoff_label", models.CharField(max_length=300)),
                ("dropoff_lat", models.FloatField()),
                ("dropoff_lng", models.FloatField()),
                (
                    "current_cycle_used_hours",
                    models.FloatField(
                        help_text="Hours already used in the rolling 8-day cycle (0-70)"
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("total_distance_miles", models.FloatField(blank=True, null=True)),
                ("total_driving_minutes", models.IntegerField(blank=True, null=True)),
                ("total_trip_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "route_geometry",
                    models.JSONField(
                        blank=True,
                        help_text="GeoJSON LineString or encoded polyline",
                        null=True,
                    ),
                ),
                (
                    "shipper_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("commodity", models.CharField(blank=True, default="", max_length=200)),
                (
                    "bol_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trips.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trips.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField()),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("origin", "Origin"),
                            ("pickup", "Pickup"),
                            ("dropoff", "Drop-off"),
                            ("fuel", "Fuel Stop"),
                            ("break_30min", "30-Minute Break"),
                            ("rest_10hr", "10-Hour Rest"),
                            ("restart_34hr", "34-Hour Restart"),
                            ("post_trip", "Post-Trip"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=300)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField()),
                ("duration_minutes", models.IntegerField()),
                ("cumulative_miles", models.FloatField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["trip", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="DutyStatusEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("off_duty", "Off Duty"),
                            ("sleeper_berth", "Sleeper Berth"),
                            ("driving", "Driving"),
                            ("on_duty_not_driving", "On Duty (Not Driving)"),
                        ],
                        max_length=25,
                    ),
                ),
                ("location_label", models.CharField(max_length=300)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("remark", models.TextField(blank=True, default="")),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_events",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["trip", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_date",
                    models.DateField(help_text="Date in home-terminal timezone"),
                ),
                ("total_miles_driving_today", models.IntegerField(default=0)),
                (
                    "total_off_duty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "total_sleeper_berth",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "total_driving",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "total_on_duty_not_driving",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "shipping_doc_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "driver_signature",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("generated_svg", models.TextField(blank=True, default="")),
                (
                    "generated_pdf",
                    models.FileField(blank=True, null=True, upload_to="logs/"),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["trip", "log_date"],
                "unique_together": {("trip", "log_date")},
            },
        ),
    ]
